#!/usr/bin/env python3
"""Moves the tile maker's design language in and out of brand/design-language.json.

The tool is one self-contained file on purpose — it has to work offline and be
handed to people outside Kai. So the token file is the source of truth and the
tool is *generated* from it, rather than fetching it at runtime.

    python3 tools/design_language.py extract   # tool  -> brand/design-language.json
    python3 tools/design_language.py inject    # json  -> tool
    python3 tools/design_language.py check     # round-trip, byte-for-byte

`check` is the one that matters: it proves the token file carries everything
the tool needs and that injecting it changes nothing.
"""
import json, pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from jsliteral import parse, JSLiteralError

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOL = ROOT / "tile-maker" / "kai-social-tile-maker.html"
JSON_OUT = ROOT / "brand" / "design-language.json"

# order matters: this is the order they appear in the tool
KEYS = ["TF", "THEMES", "WASHES", "LIGHT_INK", "ANNOUNCE", "RAMPS", "FORMATS",
        "MOTIFS", "TREATMENTS", "ACTIVITIES", "STRIP_STOPS", "ICONS", "PRESETS"]

NOTES = {
 "TF":          "Typefaces.",
 "THEMES":      "Colour themes: gradient stops, ink, accent, per-theme defaults.",
 "WASHES":      "Background washes — aurora blobs and their base stops.",
 "LIGHT_INK":   "Ink colours used when the wash is light.",
 "ANNOUNCE":    "Announcement categories and their copy defaults.",
 "RAMPS":       "Type and spacing ramps per shape. The numbers that drive layout.",
 "FORMATS":     "Output sizes and their labels.",
 "MOTIFS":      "Line motifs drawn over the wash.",
 "TREATMENTS":  "Image treatments for launch and event tiles.",
 "ACTIVITIES":  "Activity presets.",
 "STRIP_STOPS": "Stops for the brand strip along the tile edge.",
 "ICONS":       "Inline SVG path data, one entry per icon.",
 "PRESETS":     "Starting points offered in the UI.",
}


def _span(src, name):
    """(start, end) of the literal assigned to `const NAME =`, end exclusive."""
    m = re.search(r"\bconst\s+" + name + r"\s*=\s*", src)
    if not m:
        raise SystemExit(f"{name}: no `const {name} =` in the tool")
    i = m.end()
    if src[i] not in "{[":
        raise SystemExit(f"{name}: not an object or array literal")
    depth, in_str, quote, esc = 0, False, "", False
    for j in range(i, len(src)):
        c = src[j]
        if in_str:
            if esc: esc = False
            elif c == "\\": esc = True
            elif c == quote: in_str = False
            continue
        if c in "'\"`": in_str, quote = True, c
        elif c in "{[": depth += 1
        elif c in "}]":
            depth -= 1
            if depth == 0: return i, j + 1
    raise SystemExit(f"{name}: unterminated literal")


def extract():
    src = TOOL.read_text(encoding="utf-8")
    out = {"_comment": "Source of truth for the tile maker's design language. "
                       "Generated by tools/design_language.py; edit here, then "
                       "`python3 tools/design_language.py inject`.",
           "_notes": NOTES}
    for k in KEYS:
        a, b = _span(src, k)
        try:
            out[k] = parse(src[a:b], k)
        except JSLiteralError as e:
            raise SystemExit(f"{k} is not pure data, leave it in the tool: {e}")
    JSON_OUT.parent.mkdir(exist_ok=True)
    JSON_OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    return out


def _js(v, indent=0):
    """Render a value as the JS the tool expects. Keys quoted only when needed."""
    pad, pad2 = "  " * indent, "  " * (indent + 1)
    if isinstance(v, bool):  return "true" if v else "false"
    if v is None:            return "null"
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, str):
        return "'" + v.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"
    if isinstance(v, list):
        if not v: return "[]"
        return "[\n" + ",\n".join(pad2 + _js(x, indent + 1) for x in v) + "\n" + pad + "]"
    if isinstance(v, dict):
        if not v: return "{}"
        rows = []
        for k, x in v.items():
            key = k if re.fullmatch(r"[A-Za-z_$][\w$]*", k) else "'" + k + "'"
            rows.append(pad2 + key + ": " + _js(x, indent + 1))
        return "{\n" + ",\n".join(rows) + "\n" + pad + "}"
    raise SystemExit(f"cannot render {type(v).__name__}")


def inject(data=None):
    data = data or json.loads(JSON_OUT.read_text(encoding="utf-8"))
    src = TOOL.read_text(encoding="utf-8")
    for k in reversed(KEYS):                 # back to front, so spans stay valid
        a, b = _span(src, k)
        src = src[:a] + _js(data[k]) + src[b:]
    TOOL.write_text(src, encoding="utf-8")
    return src


def check():
    before = TOOL.read_text(encoding="utf-8")
    data = extract()
    inject(data)
    once = TOOL.read_text(encoding="utf-8")
    again_data = extract()
    inject(again_data)
    twice = TOOL.read_text(encoding="utf-8")
    TOOL.write_text(before, encoding="utf-8")       # leave the tool untouched
    same_values = json.dumps(data, sort_keys=True) == json.dumps(again_data, sort_keys=True)
    stable = once == twice
    print(f"  values survive a round trip : {'yes' if same_values else 'NO'}")
    print(f"  injection is idempotent     : {'yes' if stable else 'NO'}")
    print(f"  tool left unmodified        : {'yes' if TOOL.read_text(encoding='utf-8') == before else 'NO'}")
    return 0 if (same_values and stable) else 1


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd == "extract":
        d = extract()
        print(f"  wrote {JSON_OUT.relative_to(ROOT)}  ({JSON_OUT.stat().st_size/1024:.1f} KB)")
        for k in KEYS:
            n = len(d[k]) if isinstance(d[k], (dict, list)) else 1
            print(f"    {k:13} {n} entries")
    elif cmd == "inject":
        inject(); print(f"  injected into {TOOL.relative_to(ROOT)}")
    elif cmd == "check":
        sys.exit(check())
    else:
        raise SystemExit(__doc__)
